#!/usr/bin/env Rscript

################################################################################
# TCGA-PRAD | Q1 vs Q4 locked-style figures
#
# Publication figures:
#   1. PCA_Minimal.pdf
#   2. Volcano_Minimal.pdf
#   3. GSEA_EMT.pdf
#
# Internal biological control:
#   4. GSEA_Hallmark_SELECTED_EXTENDED_NES_barplot_MAIN.pdf
#
# This script:
#   - Uses the canonical VST object generated by the DESeq2 module.
#   - Uses the canonical no-signature DESeq2 and GSEA results.
#   - Uses the frozen Hallmark pathway object.
#   - Does not rerun DESeq2, VST, fgsea, GSVA, ssGSEA, or msigdbr.
################################################################################

options(stringsAsFactors = FALSE, scipen = 999)

################################################################################
# 0. Frozen analytical expectations
################################################################################

EXPECTED_Q1Q4_SAMPLES <- 250L
EXPECTED_LOW_Q1 <- 125L
EXPECTED_HIGH_Q4 <- 125L

EXPECTED_VST_GENES <- 27007L
EXPECTED_SIGNATURE_ROWS <- 41L
EXPECTED_NO_SIGNATURE_GENES <- 26966L

EXPECTED_DEG_UP <- 2851L
EXPECTED_DEG_DOWN <- 707L

EXPECTED_RANKED_GENES <- 26931L
EXPECTED_HALLMARK_PATHWAYS <- 50L
EXPECTED_SIGNIFICANT_HALLMARKS <- 32L

PADJ_THRESHOLD <- 0.05
ABS_LOG2FC_THRESHOLD <- 1

EMT_PATHWAY <- "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION"

################################################################################
# 1. Frozen graphical constants
################################################################################

BASE_FAMILY <- "Helvetica"

TITLE_SIZE <- 6
TEXT_SIZE <- 5
FONT_SIZE <- TEXT_SIZE

LINE_SIZE <- 0.20
GRID_LW <- 0.20
BORDER_LW <- 0.20

POINT_SIZE_PCA <- 0.90
POINT_ALPHA_PCA <- 0.60
POINT_SIZE_VOLCANO <- 0.42
POINT_ALPHA_VOLCANO <- 0.60

COL_LOW <- "#044C87"
COL_HIGH <- "#EF711D"

COL_NS <- "gray80"
COL_DOWN_GENE <- "#1C5DA3"
COL_UP_GENE <- "#DB0C07"

COL_ES <- "#95B300"
COL_POS <- "#DB0C07"
COL_NEG <- "#1C5DA3"

################################################################################
# 2. Project paths
################################################################################

.repo_override <- Sys.getenv("PLATELET_REPO_ROOT", unset = "")
.script_args <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
if (nzchar(.repo_override)) {
  .config_path <- file.path(
    normalizePath(.repo_override, winslash = "/", mustWork = TRUE),
    "bulk_tumor_validation", "tcga_prad", "Scripts", "00_config_paths.R"
  )
} else {
  if (length(.script_args) != 1L) {
    stop("Set PLATELET_REPO_ROOT when sourcing this script.", call. = FALSE)
  }
  .script_file <- normalizePath(
    sub("^--file=", "", .script_args[[1]]), winslash = "/", mustWork = TRUE
  )
  .config_path <- file.path(dirname(dirname(.script_file)), "00_config_paths.R")
}
source(.config_path, local = FALSE)
project_dir <- MODULE_DIR
rm(.repo_override, .script_args, .config_path)
if (exists(".script_file")) rm(.script_file)

script_relative_path <- file.path(
  "Scripts", "Q1Q4", "03_figures_Q1Q4_locked_style.R"
)

input_paths <- list(
  sample_metadata = file.path(
    GENERATED_RESULTS_DIR, "Q1Q4", "Tables", "DESeq2",
    "DESeq2_Q1Q4_sample_metadata.csv"
  ),
  full_de = file.path(
    GENERATED_RESULTS_DIR, "Q1Q4", "Tables", "DESeq2",
    "DESeq2_Q1Q4_41genes_full_results.csv"
  ),
  no_signature_de = file.path(
    GENERATED_RESULTS_DIR, "Q1Q4", "Tables", "DESeq2",
    "DESeq2_Q1Q4_41genes_no_signature_genes.csv"
  ),
  vst = file.path(
    GENERATED_RESULTS_DIR, "Q1Q4", "Objects",
    "DESeq2_Q1Q4_vst.rds"
  ),
  gsea_full = file.path(
    GENERATED_RESULTS_DIR, "Q1Q4", "Tables", "GSEA",
    "GSEA_Q1Q4_no_signature_Hallmark_full.csv"
  ),
  gsea_rank = file.path(
    GENERATED_RESULTS_DIR, "Q1Q4", "Objects", "GSEA",
    "GSEA_Q1Q4_DESeq2_Wald_stat_rank.rds"
  ),
  hallmark_pathways = file.path(
    GENERATED_RESULTS_DIR, "Q1Q4", "Objects", "GSEA",
    "GSEA_Q1Q4_Hallmark_pathways.rds"
  )
)

figure_root <- file.path(
  GENERATED_FIGURES_DIR, "Q1Q4"
)

pca_dir <- file.path(figure_root, "PCA")
volcano_dir <- file.path(figure_root, "Volcano")
gsea_dir <- file.path(figure_root, "GSEA")

figure_table_dir <- file.path(
  GENERATED_RESULTS_DIR, "Q1Q4", "Tables", "Figures"
)

log_dir <- file.path(
  GENERATED_RESULTS_DIR, "Q1Q4", "Logs"
)

invisible(lapply(
  c(pca_dir, volcano_dir, gsea_dir, figure_table_dir, log_dir),
  dir.create,
  recursive = TRUE,
  showWarnings = FALSE
))

output_paths <- list(
  pca = file.path(
    pca_dir,
    "PCA_Minimal.pdf"
  ),
  volcano = file.path(
    volcano_dir,
    "Volcano_Minimal.pdf"
  ),
  selected_hallmark_barplot = file.path(
    gsea_dir,
    "GSEA_Hallmark_SELECTED_EXTENDED_NES_barplot_MAIN.pdf"
  ),
  emt_gsea = file.path(
    gsea_dir,
    "GSEA_EMT.pdf"
  ),
  pca_scores = file.path(
    figure_table_dir,
    "PCA_Q1Q4_sample_scores.csv"
  ),
  pca_variance = file.path(
    figure_table_dir,
    "PCA_Q1Q4_variance_explained.csv"
  ),
  selected_hallmark_table = file.path(
    figure_table_dir,
    "GSEA_Hallmark_SELECTED_EXTENDED_internal_control.csv"
  ),
  metadata = file.path(
    figure_table_dir,
    "Figures_Q1Q4_metadata.json"
  ),
  qc = file.path(
    log_dir,
    "Figures_Q1Q4_locked_style_QC.txt"
  )
)

################################################################################
# 3. Helpers
################################################################################

msg <- function(...) {
  cat(format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "|", ..., "\n")
}

fail_with_qc <- function(message_text) {
  failure_lines <- c(
    "TCGA-PRAD Q1 vs Q4 locked-style figures QC",
    "================================================",
    "",
    paste0("Date/time: ", as.character(Sys.time())),
    paste0("Project dir: ", project_dir),
    paste0("Script: ", script_relative_path),
    paste0("Failure reason: ", message_text),
    "",
    "Final status: FAIL"
  )

  writeLines(failure_lines, output_paths$qc, useBytes = TRUE)
  stop(message_text, call. = FALSE)
}

fail <- function(...) {
  fail_with_qc(paste0(...))
}

require_input <- function(path, label) {
  if (!file.exists(path)) {
    fail("Missing required input: ", label, " at ", path)
  }
}

read_required_csv <- function(path, label) {
  require_input(path, label)

  utils::read.csv(
    path,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}

write_csv <- function(x, path) {
  utils::write.csv(
    as.data.frame(x),
    path,
    row.names = FALSE,
    quote = TRUE
  )
}

parse_logical_strict <- function(x, label) {
  if (is.logical(x)) {
    return(x)
  }

  value <- tolower(trimws(as.character(x)))
  output <- rep(NA, length(value))

  output[value %in% c("true", "t", "1")] <- TRUE
  output[value %in% c("false", "f", "0")] <- FALSE

  invalid <- is.na(output) & !is.na(value) & value != ""

  if (any(invalid)) {
    fail(
      "Column '", label,
      "' contains invalid logical values: ",
      paste(unique(value[invalid]), collapse = ", ")
    )
  }

  output
}

clean_hallmark_label <- function(pathway) {
  pathway_clean <- gsub("^HALLMARK_", "", pathway)
  pathway_clean <- gsub("_", " ", pathway_clean)
  pathway_clean <- tools::toTitleCase(tolower(pathway_clean))

  pathway_clean <- gsub("Tnfa", "TNF-alpha", pathway_clean)
  pathway_clean <- gsub("Nfkb", "NFkB", pathway_clean)
  pathway_clean <- gsub("Il6 Jak Stat3", "IL-6/JAK/STAT3", pathway_clean)
  pathway_clean <- gsub("Il2 Stat5", "IL2/STAT5", pathway_clean)
  pathway_clean <- gsub("Kras", "KRAS", pathway_clean)
  pathway_clean <- gsub("Tgf Beta", "TGF-beta", pathway_clean)
  pathway_clean <- gsub("P53", "p53", pathway_clean)
  pathway_clean <- gsub("Myc", "MYC", pathway_clean)
  pathway_clean <- gsub("Signaling", "signaling", pathway_clean)
  pathway_clean <- gsub("Via", "via", pathway_clean)

  pathway_clean
}

format_scientific <- function(x, digits = 2) {
  if (is.na(x)) {
    return(NA_character_)
  }

  format(
    x,
    scientific = TRUE,
    digits = digits,
    trim = TRUE
  )
}

validate_pdf <- function(path, label) {
  if (!file.exists(path)) {
    fail(label, " was not generated: ", path)
  }

  file_size <- file.info(path)$size

  if (is.na(file_size) || file_size <= 0) {
    fail(label, " is empty or invalid: ", path)
  }
}

################################################################################
# 4. Required packages
################################################################################

required_packages <- c(
  "SummarizedExperiment",
  "ggplot2",
  "patchwork",
  "jsonlite"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    logical(1),
    quietly = TRUE
  )
]

if (length(missing_packages) > 0) {
  stop(
    paste0(
      "Missing required package(s): ",
      paste(missing_packages, collapse = ", "),
      ". The script does not install packages."
    ),
    call. = FALSE
  )
}

################################################################################
# 5. Validate required inputs
################################################################################

msg("Project dir:", project_dir)

for (nm in names(input_paths)) {
  require_input(input_paths[[nm]], nm)
}

################################################################################
# 6. Load and validate the canonical Q1/Q4 sample metadata
################################################################################

msg("[1/9] Loading canonical Q1/Q4 sample metadata")

sample_metadata <- read_required_csv(
  input_paths$sample_metadata,
  "Q1/Q4 sample metadata"
)

required_metadata_columns <- c(
  "sample_id",
  "patient_id",
  "platelet_score_group",
  "Score_raw",
  "Score_z"
)

missing_metadata_columns <- setdiff(
  required_metadata_columns,
  names(sample_metadata)
)

if (length(missing_metadata_columns) > 0) {
  fail(
    "Sample metadata is missing required columns: ",
    paste(missing_metadata_columns, collapse = ", ")
  )
}

sample_metadata$sample_id <- trimws(
  as.character(sample_metadata$sample_id)
)

sample_metadata$patient_id <- trimws(
  as.character(sample_metadata$patient_id)
)

sample_metadata$platelet_score_group <- trimws(
  as.character(sample_metadata$platelet_score_group)
)

sample_metadata$Score_raw <- suppressWarnings(
  as.numeric(sample_metadata$Score_raw)
)

sample_metadata$Score_z <- suppressWarnings(
  as.numeric(sample_metadata$Score_z)
)

if (nrow(sample_metadata) != EXPECTED_Q1Q4_SAMPLES) {
  fail(
    "Expected ", EXPECTED_Q1Q4_SAMPLES,
    " Q1/Q4 samples. Observed: ",
    nrow(sample_metadata)
  )
}

if (anyDuplicated(sample_metadata$sample_id)) {
  fail("Sample metadata contains duplicated sample IDs.")
}

if (anyDuplicated(sample_metadata$patient_id)) {
  fail("Sample metadata contains duplicated patient IDs.")
}

if (
  any(!is.finite(sample_metadata$Score_raw)) ||
  any(!is.finite(sample_metadata$Score_z))
) {
  fail("Sample metadata contains non-finite score values.")
}

group_counts <- table(
  factor(
    sample_metadata$platelet_score_group,
    levels = c("LOW_Q1", "HIGH_Q4")
  )
)

if (
  as.integer(group_counts["LOW_Q1"]) != EXPECTED_LOW_Q1 ||
  as.integer(group_counts["HIGH_Q4"]) != EXPECTED_HIGH_Q4
) {
  fail(
    "Unexpected Q1/Q4 group counts. Observed: ",
    paste(
      names(group_counts),
      as.integer(group_counts),
      sep = "=",
      collapse = "; "
    )
  )
}

sample_metadata$Group <- ifelse(
  sample_metadata$platelet_score_group == "LOW_Q1",
  "Platelet Score Low",
  "Platelet Score High"
)

sample_metadata$Group <- factor(
  sample_metadata$Group,
  levels = c(
    "Platelet Score Low",
    "Platelet Score High"
  )
)

################################################################################
# 7. Load the canonical VST and define the PCA gene universe
################################################################################

msg("[2/9] Loading canonical VST object")

vst_object <- readRDS(input_paths$vst)

if (!inherits(vst_object, "SummarizedExperiment")) {
  fail(
    "VST object must inherit from SummarizedExperiment. Class: ",
    paste(class(vst_object), collapse = ", ")
  )
}

vst_matrix <- SummarizedExperiment::assay(vst_object)

if (is.null(dim(vst_matrix)) || length(dim(vst_matrix)) != 2) {
  fail("VST assay is not a two-dimensional matrix-like object.")
}

if (nrow(vst_matrix) != EXPECTED_VST_GENES) {
  fail(
    "Expected ", EXPECTED_VST_GENES,
    " genes in the VST object. Observed: ",
    nrow(vst_matrix)
  )
}

if (ncol(vst_matrix) != EXPECTED_Q1Q4_SAMPLES) {
  fail(
    "Expected ", EXPECTED_Q1Q4_SAMPLES,
    " samples in the VST object. Observed: ",
    ncol(vst_matrix)
  )
}

if (
  any(!is.finite(vst_matrix)) ||
  anyDuplicated(rownames(vst_matrix)) ||
  anyDuplicated(colnames(vst_matrix))
) {
  fail(
    "VST matrix contains non-finite values or duplicated row/column names."
  )
}

if (!setequal(colnames(vst_matrix), sample_metadata$sample_id)) {
  fail("VST and sample metadata contain different sample sets.")
}

sample_metadata <- sample_metadata[
  match(colnames(vst_matrix), sample_metadata$sample_id),
  ,
  drop = FALSE
]

if (!identical(sample_metadata$sample_id, colnames(vst_matrix))) {
  fail("VST and sample metadata could not be aligned.")
}

full_de <- read_required_csv(
  input_paths$full_de,
  "full DESeq2 result table"
)

required_full_de_columns <- c(
  "ensembl_id",
  "is_signature_gene"
)

missing_full_de_columns <- setdiff(
  required_full_de_columns,
  names(full_de)
)

if (length(missing_full_de_columns) > 0) {
  fail(
    "Full DESeq2 table is missing required columns: ",
    paste(missing_full_de_columns, collapse = ", ")
  )
}

full_de$ensembl_id <- trimws(as.character(full_de$ensembl_id))

full_de$is_signature_gene <- parse_logical_strict(
  full_de$is_signature_gene,
  "is_signature_gene"
)

if (nrow(full_de) != EXPECTED_VST_GENES) {
  fail(
    "Expected ", EXPECTED_VST_GENES,
    " rows in the full DESeq2 table. Observed: ",
    nrow(full_de)
  )
}

if (anyDuplicated(full_de$ensembl_id)) {
  fail("Full DESeq2 table contains duplicated Ensembl IDs.")
}

if (!setequal(rownames(vst_matrix), full_de$ensembl_id)) {
  fail("VST and full DESeq2 table contain different gene sets.")
}

full_de_order <- match(
  rownames(vst_matrix),
  full_de$ensembl_id
)

signature_mask <- full_de$is_signature_gene[full_de_order]

if (any(is.na(signature_mask))) {
  fail("Signature annotation could not be aligned to all VST rows.")
}

n_signature_rows <- sum(signature_mask)
n_no_signature_rows <- sum(!signature_mask)

if (n_signature_rows != EXPECTED_SIGNATURE_ROWS) {
  fail(
    "Expected ", EXPECTED_SIGNATURE_ROWS,
    " signature rows in the VST object. Observed: ",
    n_signature_rows
  )
}

if (n_no_signature_rows != EXPECTED_NO_SIGNATURE_GENES) {
  fail(
    "Expected ", EXPECTED_NO_SIGNATURE_GENES,
    " no-signature VST genes. Observed: ",
    n_no_signature_rows
  )
}

vst_pca <- vst_matrix[
  !signature_mask,
  ,
  drop = FALSE
]

################################################################################
# 8. PCA
################################################################################

msg("[3/9] Generating locked-style PCA")

pca_object <- stats::prcomp(
  t(vst_pca),
  center = TRUE,
  scale. = FALSE
)

variance_explained <- (
  pca_object$sdev^2 /
    sum(pca_object$sdev^2)
) * 100

pca_scores <- data.frame(
  sample_id = rownames(pca_object$x),
  PC1 = as.numeric(pca_object$x[, 1]),
  PC2 = as.numeric(pca_object$x[, 2]),
  stringsAsFactors = FALSE
)

metadata_order <- match(
  pca_scores$sample_id,
  sample_metadata$sample_id
)

pca_scores$patient_id <- sample_metadata$patient_id[metadata_order]

pca_scores$platelet_score_group <-
  sample_metadata$platelet_score_group[metadata_order]

pca_scores$Group <- sample_metadata$Group[metadata_order]
pca_scores$Score_raw <- sample_metadata$Score_raw[metadata_order]
pca_scores$Score_z <- sample_metadata$Score_z[metadata_order]

if (any(is.na(pca_scores$Group))) {
  fail("PCA scores could not be aligned to sample groups.")
}

variance_table <- data.frame(
  principal_component = paste0(
    "PC",
    seq_along(variance_explained)
  ),
  variance_explained_percent = as.numeric(
    variance_explained
  ),
  cumulative_variance_percent = cumsum(
    variance_explained
  ),
  stringsAsFactors = FALSE
)

write_csv(pca_scores, output_paths$pca_scores)
write_csv(variance_table, output_paths$pca_variance)

x_range <- range(pca_scores$PC1, na.rm = TRUE)
y_range <- range(pca_scores$PC2, na.rm = TRUE)

x_span <- diff(x_range)
y_span <- diff(y_range)

if (
  !is.finite(x_span) ||
  x_span == 0 ||
  !is.finite(y_span) ||
  y_span == 0
) {
  fail("PCA plotting range is zero or non-finite.")
}

x_label <- max(pca_scores$PC1, na.rm = TRUE) - 0.005 * x_span
y_label_low <- min(pca_scores$PC2, na.rm = TRUE) - 0.11 * y_span
y_label_high <- min(pca_scores$PC2, na.rm = TRUE) - 0.20 * y_span

pca_plot <- ggplot2::ggplot(
  pca_scores,
  ggplot2::aes(
    x = PC1,
    y = PC2,
    color = Group
  )
) +
  ggplot2::geom_point(
    size = POINT_SIZE_PCA,
    alpha = POINT_ALPHA_PCA,
    shape = 16
  ) +
  ggplot2::scale_color_manual(
    values = c(
      "Platelet Score Low" = COL_LOW,
      "Platelet Score High" = COL_HIGH
    ),
    name = NULL
  ) +
  ggplot2::annotate(
    "text",
    x = x_label,
    y = y_label_low,
    label = "Platelet score low",
    hjust = 1,
    vjust = 0.5,
    color = COL_LOW,
    family = BASE_FAMILY,
    fontface = "plain",
    size = 4.5 / ggplot2::.pt
  ) +
  ggplot2::annotate(
    "text",
    x = x_label,
    y = y_label_high,
    label = "Platelet score high",
    hjust = 1,
    vjust = 0.5,
    color = COL_HIGH,
    family = BASE_FAMILY,
    fontface = "plain",
    size = 4.5 / ggplot2::.pt
  ) +
  ggplot2::labs(
    x = paste0(
      "PC1 (",
      round(variance_explained[1], 2),
      "%)"
    ),
    y = paste0(
      "PC2 (",
      round(variance_explained[2], 2),
      "%)"
    )
  ) +
  ggplot2::theme_bw(
    base_size = TEXT_SIZE,
    base_family = BASE_FAMILY
  ) +
  ggplot2::theme(
    text = ggplot2::element_text(
      family = BASE_FAMILY,
      size = TEXT_SIZE,
      color = "black"
    ),
    legend.position = "none",
    axis.title = ggplot2::element_text(
      size = 4.5,
      color = "black"
    ),
    axis.text = ggplot2::element_text(
      size = 4.3,
      color = "black"
    ),
    axis.ticks = ggplot2::element_line(
      linewidth = 0.20,
      color = "black"
    ),
    panel.grid.major = ggplot2::element_line(
      linewidth = 0.14,
      color = "grey95"
    ),
    panel.grid.minor = ggplot2::element_blank(),
    panel.border = ggplot2::element_rect(
      linewidth = 0.20,
      colour = "black",
      fill = NA
    ),
    plot.margin = grid::unit(
      c(2, 2, 2, 2),
      "mm"
    )
  )

ggplot2::ggsave(
  filename = output_paths$pca,
  plot = pca_plot,
  width = 4.2,
  height = 3.8,
  units = "cm",
  device = "pdf"
)

validate_pdf(output_paths$pca, "PCA figure")

################################################################################
# 9. Volcano
################################################################################

msg("[4/9] Generating locked-style volcano plot")

no_signature_de <- read_required_csv(
  input_paths$no_signature_de,
  "no-signature DESeq2 result table"
)

required_no_signature_columns <- c(
  "ensembl_id",
  "gene_name",
  "log2FoldChange",
  "log2FoldChange_shrunken",
  "padj",
  "is_signature_gene"
)

missing_no_signature_columns <- setdiff(
  required_no_signature_columns,
  names(no_signature_de)
)

if (length(missing_no_signature_columns) > 0) {
  fail(
    "No-signature DESeq2 table is missing required columns: ",
    paste(missing_no_signature_columns, collapse = ", ")
  )
}

if (nrow(no_signature_de) != EXPECTED_NO_SIGNATURE_GENES) {
  fail(
    "Expected ", EXPECTED_NO_SIGNATURE_GENES,
    " no-signature DESeq2 rows. Observed: ",
    nrow(no_signature_de)
  )
}

no_signature_de$is_signature_gene <- parse_logical_strict(
  no_signature_de$is_signature_gene,
  "is_signature_gene"
)

if (any(no_signature_de$is_signature_gene %in% TRUE, na.rm = TRUE)) {
  fail("No-signature DESeq2 input still contains signature genes.")
}

no_signature_de$log2FoldChange <- suppressWarnings(
  as.numeric(no_signature_de$log2FoldChange)
)

no_signature_de$log2FoldChange_shrunken <- suppressWarnings(
  as.numeric(no_signature_de$log2FoldChange_shrunken)
)

no_signature_de$padj <- suppressWarnings(
  as.numeric(no_signature_de$padj)
)

plot_log2fc <- no_signature_de$log2FoldChange_shrunken

fallback_rows <- !is.finite(plot_log2fc) &
  is.finite(no_signature_de$log2FoldChange)

plot_log2fc[fallback_rows] <-
  no_signature_de$log2FoldChange[fallback_rows]

if (any(!is.finite(plot_log2fc))) {
  fail(
    "Volcano effect-size column contains non-finite values after fallback."
  )
}

negative_log10_fdr <- -log10(
  pmax(no_signature_de$padj, 1e-300)
)

significance <- ifelse(
  !is.na(no_signature_de$padj) &
    no_signature_de$padj < PADJ_THRESHOLD &
    plot_log2fc > ABS_LOG2FC_THRESHOLD,
  "Upregulated",
  ifelse(
    !is.na(no_signature_de$padj) &
      no_signature_de$padj < PADJ_THRESHOLD &
      plot_log2fc < -ABS_LOG2FC_THRESHOLD,
    "Downregulated",
    "Not significant"
  )
)

volcano_data <- data.frame(
  ensembl_id = no_signature_de$ensembl_id,
  gene_name = no_signature_de$gene_name,
  log2FoldChange_plot = plot_log2fc,
  neg_log10_padj = negative_log10_fdr,
  Significance = factor(
    significance,
    levels = c(
      "Downregulated",
      "Not significant",
      "Upregulated"
    )
  ),
  stringsAsFactors = FALSE
)

n_up <- sum(
  volcano_data$Significance == "Upregulated",
  na.rm = TRUE
)

n_down <- sum(
  volcano_data$Significance == "Downregulated",
  na.rm = TRUE
)

if (n_up != EXPECTED_DEG_UP || n_down != EXPECTED_DEG_DOWN) {
  fail(
    "Unexpected volcano DEG counts. Expected UP=",
    EXPECTED_DEG_UP,
    " and DOWN=",
    EXPECTED_DEG_DOWN,
    "; observed UP=",
    n_up,
    " and DOWN=",
    n_down,
    "."
  )
}

xmax <- max(
  abs(volcano_data$log2FoldChange_plot),
  na.rm = TRUE
)

xlim_value <- max(
  3,
  min(
    8,
    1.1 * xmax
  )
)

volcano_plot <- ggplot2::ggplot(
  volcano_data,
  ggplot2::aes(
    x = log2FoldChange_plot,
    y = neg_log10_padj
  )
) +
  ggplot2::geom_point(
    ggplot2::aes(color = Significance),
    size = POINT_SIZE_VOLCANO,
    alpha = POINT_ALPHA_VOLCANO,
    shape = 16
  ) +
  ggplot2::geom_vline(
    xintercept = c(
      -ABS_LOG2FC_THRESHOLD,
      ABS_LOG2FC_THRESHOLD
    ),
    linetype = "dashed",
    linewidth = LINE_SIZE,
    alpha = 0.4,
    color = "black"
  ) +
  ggplot2::geom_hline(
    yintercept = -log10(PADJ_THRESHOLD),
    linetype = "dashed",
    linewidth = LINE_SIZE,
    alpha = 0.4,
    color = "black"
  ) +
  ggplot2::scale_color_manual(
    breaks = c(
      "Downregulated",
      "Not significant",
      "Upregulated"
    ),
    values = c(
      "Downregulated" = COL_DOWN_GENE,
      "Not significant" = COL_NS,
      "Upregulated" = COL_UP_GENE
    ),
    name = NULL,
    labels = c(
      "Downregulated",
      "NS",
      "Upregulated"
    )
  ) +
  ggplot2::coord_cartesian(
    xlim = c(-xlim_value, xlim_value)
  ) +
  ggplot2::labs(
    x = expression(log[2] ~ "fold change"),
    y = expression(-log[10] ~ "FDR")
  ) +
  ggplot2::theme_bw(
    base_size = TEXT_SIZE,
    base_family = BASE_FAMILY
  ) +
  ggplot2::theme(
    text = ggplot2::element_text(
      family = BASE_FAMILY,
      size = TEXT_SIZE
    ),
    legend.position = "none",
    axis.title = ggplot2::element_text(
      size = 4.6
    ),
    axis.text = ggplot2::element_text(
      size = 4.3,
      color = "black"
    ),
    axis.ticks = ggplot2::element_line(
      linewidth = LINE_SIZE
    ),
    panel.grid.major = ggplot2::element_line(
      linewidth = GRID_LW
    ),
    panel.grid.minor = ggplot2::element_blank(),
    panel.border = ggplot2::element_rect(
      linewidth = BORDER_LW
    ),
    plot.margin = grid::unit(
      c(2, 2, 2, 2),
      "mm"
    )
  )

ggplot2::ggsave(
  filename = output_paths$volcano,
  plot = volcano_plot,
  width = 4.1,
  height = 3.7,
  units = "cm",
  device = "pdf"
)

validate_pdf(output_paths$volcano, "Volcano figure")

################################################################################
# 10. Load canonical GSEA outputs
################################################################################

msg("[5/9] Loading canonical Hallmark GSEA outputs")

gsea_full <- read_required_csv(
  input_paths$gsea_full,
  "complete Hallmark GSEA table"
)

required_gsea_columns <- c(
  "pathway",
  "ES",
  "NES",
  "pval",
  "padj",
  "size",
  "leadingEdge"
)

missing_gsea_columns <- setdiff(
  required_gsea_columns,
  names(gsea_full)
)

if (length(missing_gsea_columns) > 0) {
  fail(
    "GSEA table is missing required columns: ",
    paste(missing_gsea_columns, collapse = ", ")
  )
}

gsea_full$ES <- suppressWarnings(as.numeric(gsea_full$ES))
gsea_full$NES <- suppressWarnings(as.numeric(gsea_full$NES))
gsea_full$pval <- suppressWarnings(as.numeric(gsea_full$pval))
gsea_full$padj <- suppressWarnings(as.numeric(gsea_full$padj))
gsea_full$size <- suppressWarnings(as.numeric(gsea_full$size))

if (nrow(gsea_full) != EXPECTED_HALLMARK_PATHWAYS) {
  fail(
    "Expected ", EXPECTED_HALLMARK_PATHWAYS,
    " Hallmark pathways. Observed: ",
    nrow(gsea_full)
  )
}

if (anyDuplicated(gsea_full$pathway)) {
  fail("GSEA table contains duplicated pathway names.")
}

if (
  any(!is.finite(gsea_full$ES)) ||
  any(!is.finite(gsea_full$NES))
) {
  fail("GSEA table contains non-finite ES or NES values.")
}

n_significant_hallmarks <- sum(
  !is.na(gsea_full$padj) &
    gsea_full$padj < PADJ_THRESHOLD
)

if (n_significant_hallmarks != EXPECTED_SIGNIFICANT_HALLMARKS) {
  fail(
    "Expected ", EXPECTED_SIGNIFICANT_HALLMARKS,
    " significant Hallmarks. Observed: ",
    n_significant_hallmarks
  )
}

################################################################################
# 11. Selected extended Hallmark barplot: internal control
################################################################################

msg("[6/9] Generating selected Hallmark internal-control barplot")

selected_hallmark_ids <- c(
  "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION",
  "HALLMARK_TGF_BETA_SIGNALING",
  "HALLMARK_APICAL_JUNCTION",
  "HALLMARK_COAGULATION",
  "HALLMARK_HYPOXIA",
  "HALLMARK_ANGIOGENESIS",
  "HALLMARK_GLYCOLYSIS",
  "HALLMARK_APOPTOSIS",
  "HALLMARK_P53_PATHWAY",
  "HALLMARK_KRAS_SIGNALING_UP",
  "HALLMARK_INFLAMMATORY_RESPONSE",
  "HALLMARK_COMPLEMENT",
  "HALLMARK_ANDROGEN_RESPONSE",
  "HALLMARK_MYC_TARGETS_V1",
  "HALLMARK_KRAS_SIGNALING_DN"
)

missing_selected_pathways <- setdiff(
  selected_hallmark_ids,
  gsea_full$pathway
)

if (length(missing_selected_pathways) > 0) {
  fail(
    "Selected Hallmark pathways are absent from the GSEA table: ",
    paste(missing_selected_pathways, collapse = ", ")
  )
}

selected_hallmarks <- gsea_full[
  gsea_full$pathway %in% selected_hallmark_ids &
    !is.na(gsea_full$padj) &
    gsea_full$padj < PADJ_THRESHOLD,
  ,
  drop = FALSE
]

if (nrow(selected_hallmarks) == 0) {
  fail(
    "No selected extended Hallmark pathways passed FDR < 0.05."
  )
}

selected_hallmarks$pathway_clean <- clean_hallmark_label(
  selected_hallmarks$pathway
)

selected_hallmarks$NES_direction <- ifelse(
  selected_hallmarks$NES > 0,
  "High platelet score",
  ifelse(
    selected_hallmarks$NES < 0,
    "Low platelet score",
    "Neutral"
  )
)

selected_order <- order(
  selected_hallmarks$NES < 0,
  -selected_hallmarks$NES
)

selected_hallmarks <- selected_hallmarks[
  selected_order,
  ,
  drop = FALSE
]

selected_hallmarks$pathway_clean <- factor(
  selected_hallmarks$pathway_clean,
  levels = rev(selected_hallmarks$pathway_clean)
)

write_csv(
  selected_hallmarks,
  output_paths$selected_hallmark_table
)

x_min_data <- min(
  c(selected_hallmarks$NES, 0),
  na.rm = TRUE
)

x_max_data <- max(
  c(selected_hallmarks$NES, 0),
  na.rm = TRUE
)

x_min <- floor(x_min_data)
x_max <- ceiling(x_max_data)

x_breaks <- sort(unique(c(
  seq(0, x_min, by = -2),
  seq(0, x_max, by = 2)
)))

selected_hallmark_plot <- ggplot2::ggplot(
  selected_hallmarks,
  ggplot2::aes(
    x = NES,
    y = pathway_clean,
    fill = NES_direction
  )
) +
  ggplot2::geom_col(
    width = 0.62
  ) +
  ggplot2::geom_vline(
    xintercept = 0,
    linewidth = 0.20,
    color = "black"
  ) +
  ggplot2::scale_fill_manual(
    values = c(
      "High platelet score" = COL_UP_GENE,
      "Low platelet score" = COL_DOWN_GENE,
      "Neutral" = COL_NS
    )
  ) +
  ggplot2::scale_x_continuous(
    limits = c(x_min, x_max),
    breaks = x_breaks,
    expand = ggplot2::expansion(
      mult = c(0, 0.02)
    )
  ) +
  ggplot2::labs(
    x = "Normalized Enrichment\nScore (NES)",
    y = NULL,
    title = NULL
  ) +
  ggplot2::theme_classic(
    base_family = BASE_FAMILY,
    base_size = TEXT_SIZE
  ) +
  ggplot2::theme(
    legend.position = "none",
    axis.line.x = ggplot2::element_line(
      linewidth = 0.20,
      color = "black"
    ),
    axis.line.y = ggplot2::element_line(
      linewidth = 0.20,
      color = "black"
    ),
    axis.title.x = ggplot2::element_text(
      size = 4.2
    ),
    axis.title.y = ggplot2::element_blank(),
    axis.text.x = ggplot2::element_text(
      size = 4,
      color = "black"
    ),
    axis.text.y = ggplot2::element_text(
      size = 4.5,
      color = "black"
    ),
    axis.ticks.x = ggplot2::element_line(
      linewidth = 0.20,
      color = "black"
    ),
    axis.ticks.y = ggplot2::element_line(
      linewidth = 0.20,
      color = "black"
    ),
    axis.ticks.length = grid::unit(
      0.35,
      "mm"
    ),
    panel.grid.major = ggplot2::element_blank(),
    panel.grid.minor = ggplot2::element_blank(),
    plot.margin = ggplot2::margin(
      0.7,
      1.0,
      0.9,
      1.6,
      "mm"
    )
  )

selected_barplot_height <- max(
  3.95,
  0.22 * nrow(selected_hallmarks) + 1
)

ggplot2::ggsave(
  filename = output_paths$selected_hallmark_barplot,
  plot = selected_hallmark_plot,
  width = 4.9,
  height = selected_barplot_height,
  units = "cm",
  device = "pdf"
)

validate_pdf(
  output_paths$selected_hallmark_barplot,
  "Selected Hallmark internal-control barplot"
)

################################################################################
# 12. EMT GSEA running-score plot
################################################################################

msg("[7/9] Generating locked-style EMT GSEA curve")

ranks <- readRDS(input_paths$gsea_rank)

if (
  !is.numeric(ranks) ||
  is.null(names(ranks)) ||
  any(names(ranks) == "") ||
  any(!is.finite(ranks))
) {
  fail("Canonical GSEA rank object is invalid.")
}

if (length(ranks) != EXPECTED_RANKED_GENES) {
  fail(
    "Expected ", EXPECTED_RANKED_GENES,
    " ranked genes. Observed: ",
    length(ranks)
  )
}

if (anyDuplicated(names(ranks))) {
  fail("Canonical GSEA rank object contains duplicated gene names.")
}

ranks <- sort(ranks, decreasing = TRUE)

hallmark_pathways <- readRDS(
  input_paths$hallmark_pathways
)

if (!is.list(hallmark_pathways)) {
  fail("Frozen Hallmark pathway object is not a list.")
}

if (length(hallmark_pathways) != EXPECTED_HALLMARK_PATHWAYS) {
  fail(
    "Expected ", EXPECTED_HALLMARK_PATHWAYS,
    " pathways in the frozen Hallmark object. Observed: ",
    length(hallmark_pathways)
  )
}

if (!EMT_PATHWAY %in% names(hallmark_pathways)) {
  fail(
    "Frozen Hallmark pathway object does not contain ",
    EMT_PATHWAY,
    "."
  )
}

emt_genes <- unique(
  as.character(
    hallmark_pathways[[EMT_PATHWAY]]
  )
)

emt_genes_in_rank <- intersect(
  emt_genes,
  names(ranks)
)

number_ranked_genes <- length(ranks)
number_emt_genes <- length(emt_genes_in_rank)

if (number_emt_genes < 10) {
  fail(
    "Too few EMT genes were found in the canonical rank: ",
    number_emt_genes
  )
}

hit_positions <- which(
  names(ranks) %in% emt_genes_in_rank
)

hit_indicator <- logical(number_ranked_genes)
hit_indicator[hit_positions] <- TRUE

hit_weights <- abs(ranks[hit_positions])
hit_weights <- hit_weights / sum(hit_weights)

miss_penalty <- 1 / (
  number_ranked_genes - number_emt_genes
)

running_score <- numeric(number_ranked_genes)

current_score <- 0
hit_index <- 1L

for (i in seq_len(number_ranked_genes)) {
  if (hit_indicator[i]) {
    current_score <- current_score + hit_weights[hit_index]
    hit_index <- hit_index + 1L
  } else {
    current_score <- current_score - miss_penalty
  }

  running_score[i] <- current_score
}

positive_es <- max(running_score, na.rm = TRUE)
negative_es <- min(running_score, na.rm = TRUE)

manual_es <- if (
  abs(positive_es) >= abs(negative_es)
) {
  positive_es
} else {
  negative_es
}

emt_result <- gsea_full[
  gsea_full$pathway == EMT_PATHWAY,
  ,
  drop = FALSE
]

if (nrow(emt_result) != 1L) {
  fail(
    "Expected exactly one EMT result in the GSEA table. Observed: ",
    nrow(emt_result)
  )
}

emt_nes <- emt_result$NES
emt_fdr <- emt_result$padj
emt_fgsea_es <- emt_result$ES

manual_es_difference <- abs(
  manual_es - emt_fgsea_es
)

if (!is.finite(manual_es_difference)) {
  fail("Manual and canonical EMT ES values could not be compared.")
}

if (manual_es_difference > 1e-6) {
  fail(
    "Manual EMT running-score reconstruction does not match the canonical ",
    "fgsea ES. Difference: ",
    format(manual_es_difference, scientific = TRUE)
  )
}

metrics_block <- paste(
  c(
    paste0(
      "NES = ",
      round(emt_nes, 2)
    ),
    paste0(
      "FDR = ",
      format_scientific(emt_fdr, digits = 2)
    )
  ),
  collapse = "\n"
)

df_es <- data.frame(
  rank = seq_len(number_ranked_genes),
  ES = running_score
)

df_hits <- data.frame(
  rank = hit_positions
)

df_metric <- data.frame(
  rank = seq_len(number_ranked_genes),
  metric = as.numeric(ranks)
)

lower_quantile <- as.numeric(
  stats::quantile(
    df_metric$metric,
    0.01,
    na.rm = TRUE
  )
)

upper_quantile <- as.numeric(
  stats::quantile(
    df_metric$metric,
    0.99,
    na.rm = TRUE
  )
)

df_metric$metric_clip <- pmax(
  lower_quantile,
  pmin(
    upper_quantile,
    df_metric$metric
  )
)

df_strip <- data.frame(
  rank = df_metric$rank,
  y = 0,
  z = df_metric$metric_clip
)

GSEA_TITLE_SIZE <- 5
GSEA_FONT_SIZE <- 5

GSEA_LINE_LW <- 0.16
GSEA_GRID_LW <- 0.16
GSEA_BORDER_LW <- 0.20

theme_nature <- ggplot2::theme_classic(
  base_size = GSEA_FONT_SIZE,
  base_family = BASE_FAMILY
) +
  ggplot2::theme(
    axis.line = ggplot2::element_blank(),
    panel.grid.minor = ggplot2::element_blank(),
    panel.grid.major = ggplot2::element_line(
      linewidth = GSEA_GRID_LW,
      colour = "grey90"
    ),
    axis.ticks = ggplot2::element_line(
      linewidth = GSEA_LINE_LW
    ),
    axis.ticks.length = grid::unit(
      0.5,
      "mm"
    ),
    panel.border = ggplot2::element_rect(
      linewidth = GSEA_BORDER_LW,
      colour = "black",
      fill = NA
    ),
    plot.title = ggplot2::element_text(
      face = "plain",
      size = GSEA_TITLE_SIZE,
      hjust = 0.5,
      margin = ggplot2::margin(b = 0)
    ),
    plot.subtitle = ggplot2::element_text(
      size = GSEA_FONT_SIZE,
      hjust = 0
    ),
    axis.title = ggplot2::element_text(
      size = 4.35
    ),
    axis.text = ggplot2::element_text(
      size = 4.35
    ),
    plot.margin = grid::unit(
      c(1, 1, 1, 1),
      "mm"
    )
  )

p_es <- ggplot2::ggplot(
  df_es,
  ggplot2::aes(
    x = rank,
    y = ES
  )
) +
  ggplot2::geom_hline(
    yintercept = 0,
    linewidth = GSEA_LINE_LW,
    color = "black",
    alpha = 0.6
  ) +
  ggplot2::geom_line(
    linewidth = 0.75,
    color = COL_ES,
    lineend = "round"
  ) +
  ggplot2::labs(
    title = "Hallmark epithelial-mesenchymal transition",
    x = NULL,
    y = "Running enrichment\nscore"
  ) +
  ggplot2::annotate(
    "text",
    x = Inf,
    y = Inf,
    label = metrics_block,
    hjust = 1.1,
    vjust = 1.26,
    lineheight = 0.84,
    family = BASE_FAMILY,
    size = GSEA_FONT_SIZE / ggplot2::.pt
  ) +
  ggplot2::coord_cartesian(
    clip = "off"
  ) +
  theme_nature +
  ggplot2::theme(
    panel.grid.major = ggplot2::element_blank(),
    panel.grid.minor = ggplot2::element_blank(),
    axis.text.x = ggplot2::element_blank(),
    axis.ticks.x = ggplot2::element_blank(),
    plot.title = ggplot2::element_text(
      face = "plain",
      size = GSEA_TITLE_SIZE,
      hjust = 0.5,
      margin = ggplot2::margin(
        b = 0.40,
        unit = "mm"
      )
    ),
    plot.margin = grid::unit(
      c(0.8, 1, 0.5, 1),
      "mm"
    )
  )

p_hits <- ggplot2::ggplot() +
  ggplot2::geom_segment(
    data = df_hits,
    ggplot2::aes(
      x = rank,
      xend = rank,
      y = 1,
      yend = 0
    ),
    linewidth = 0.10,
    color = "black",
    alpha = 0.60
  ) +
  ggplot2::geom_tile(
    data = df_strip,
    ggplot2::aes(
      x = rank,
      y = -0.33,
      fill = z
    ),
    height = 0.55,
    width = 1
  ) +
  ggplot2::scale_fill_gradient2(
    low = COL_NEG,
    mid = "white",
    high = COL_POS,
    midpoint = 0,
    guide = "none"
  ) +
  ggplot2::annotate(
    "text",
    x = 1,
    y = -0.92,
    label = "Platelet score high",
    hjust = 0,
    vjust = 0.5,
    family = BASE_FAMILY,
    fontface = "plain",
    size = 4 / ggplot2::.pt
  ) +
  ggplot2::annotate(
    "text",
    x = number_ranked_genes,
    y = -0.92,
    label = "Platelet score low",
    hjust = 1,
    vjust = 0.5,
    family = BASE_FAMILY,
    fontface = "plain",
    size = 4 / ggplot2::.pt
  ) +
  ggplot2::coord_cartesian(
    xlim = c(1, number_ranked_genes),
    ylim = c(-0.95, 1.02),
    clip = "off"
  ) +
  ggplot2::theme_void(
    base_family = BASE_FAMILY,
    base_size = GSEA_FONT_SIZE
  ) +
  ggplot2::theme(
    plot.margin = grid::unit(
      c(0.2, 1, 0.2, 1),
      "mm"
    )
  )

p_metric <- ggplot2::ggplot(
  df_metric,
  ggplot2::aes(
    x = rank,
    y = metric
  )
) +
  ggplot2::geom_hline(
    yintercept = 0,
    linewidth = GSEA_LINE_LW,
    color = "black",
    alpha = 0.75
  ) +
  ggplot2::geom_area(
    fill = "grey85",
    alpha = 1
  ) +
  ggplot2::geom_line(
    linewidth = 0.20,
    color = "grey55"
  ) +
  ggplot2::labs(
    x = "Rank in ordered dataset",
    y = "Ranking metric\n(Wald statistic)"
  ) +
  theme_nature +
  ggplot2::theme(
    plot.margin = grid::unit(
      c(0.5, 1, 1, 1),
      "mm"
    )
  )

emt_gsea_plot <- patchwork::wrap_plots(
  p_es,
  p_hits,
  p_metric,
  ncol = 1,
  heights = c(2.0, 0.55, 0.85)
) &
  ggplot2::theme(
    plot.margin = ggplot2::margin(
      0.6,
      0.6,
      0.6,
      0.6,
      "pt"
    )
  )

ggplot2::ggsave(
  filename = output_paths$emt_gsea,
  plot = emt_gsea_plot,
  width = 4.2,
  height = 3.9,
  units = "cm",
  device = "pdf"
)

validate_pdf(output_paths$emt_gsea, "EMT GSEA figure")

################################################################################
# 13. Metadata
################################################################################

msg("[8/9] Writing figure metadata")

metadata <- list(
  date_time = as.character(Sys.time()),
  project_dir = project_dir,
  script = script_relative_path,
  project = "tcga_prad",
  analysis = "Q1 vs Q4 locked-style figures",
  analytic_hierarchy = "primary transcriptomic analysis",
  inputs = input_paths,
  cohort = list(
    samples = nrow(sample_metadata),
    LOW_Q1 = as.integer(group_counts["LOW_Q1"]),
    HIGH_Q4 = as.integer(group_counts["HIGH_Q4"]),
    unique_patients = length(unique(sample_metadata$patient_id))
  ),
  PCA = list(
    status = "publication_figure",
    VST_recalculated = FALSE,
    genes_in_canonical_VST = nrow(vst_matrix),
    signature_rows_excluded = n_signature_rows,
    genes_used = nrow(vst_pca),
    PC1_variance_percent = unname(variance_explained[1]),
    PC2_variance_percent = unname(variance_explained[2]),
    output = output_paths$pca
  ),
  volcano = list(
    status = "publication_figure",
    effect_size = paste0(
      "apeglm-shrunken log2FC; unshrunken fallback only if ",
      "shrunken value is unavailable"
    ),
    fallback_rows = sum(fallback_rows),
    padj_threshold = PADJ_THRESHOLD,
    absolute_log2FC_threshold = ABS_LOG2FC_THRESHOLD,
    UP_HIGH_Q4 = n_up,
    DOWN_HIGH_Q4 = n_down,
    output = output_paths$volcano
  ),
  selected_Hallmark_barplot = list(
    status = "internal_control_not_current_manuscript_panel",
    selected_pathways_requested = length(selected_hallmark_ids),
    selected_pathways_significant = nrow(selected_hallmarks),
    significant_filter = "padj < 0.05",
    output = output_paths$selected_hallmark_barplot
  ),
  EMT_GSEA = list(
    status = "publication_figure",
    pathway = EMT_PATHWAY,
    ranked_genes = number_ranked_genes,
    EMT_genes_in_rank = number_emt_genes,
    manual_ES = manual_es,
    canonical_fgsea_ES = emt_fgsea_es,
    ES_absolute_difference = manual_es_difference,
    NES = emt_nes,
    FDR = emt_fdr,
    output = output_paths$emt_gsea
  ),
  aesthetics = list(
    family = BASE_FAMILY,
    LOW_Q1_color = COL_LOW,
    HIGH_Q4_color = COL_HIGH,
    DEG_down_color = COL_DOWN_GENE,
    DEG_up_color = COL_UP_GENE,
    EMT_curve_color = COL_ES
  ),
  outputs = output_paths,
  exclusions = list(
    all_significant_Hallmark_barplot = "not generated",
    DEG_heatmap = "not generated",
    Q1Q4_EMT_two_column_heatmap = "not generated"
  ),
  reproducibility = list(
    R_version = R.version.string,
    SummarizedExperiment_version = as.character(
      utils::packageVersion("SummarizedExperiment")
    ),
    ggplot2_version = as.character(
      utils::packageVersion("ggplot2")
    ),
    patchwork_version = as.character(
      utils::packageVersion("patchwork")
    ),
    jsonlite_version = as.character(
      utils::packageVersion("jsonlite")
    )
  ),
  qc_status = "PASS"
)

jsonlite::write_json(
  metadata,
  output_paths$metadata,
  pretty = TRUE,
  auto_unbox = TRUE,
  null = "null",
  digits = NA
)

################################################################################
# 14. Final QC
################################################################################

msg("[9/9] Writing final QC report")

qc_lines <- c(
  "TCGA-PRAD Q1 vs Q4 locked-style figures QC",
  "================================================",
  "",
  paste0("Date/time: ", as.character(Sys.time())),
  paste0("Project dir: ", project_dir),
  paste0("Script: ", script_relative_path),
  "",
  "1. Safety and provenance",
  "  DESeq2 rerun: FALSE",
  "  VST recalculated: FALSE",
  "  fgsea rerun: FALSE",
  "  msigdbr queried: FALSE",
  "  GSVA or ssGSEA run: FALSE",
  "  Canonical precomputed analytical objects used: TRUE",
  "",
  "2. Cohort",
  paste0("  Q1/Q4 samples: ", nrow(sample_metadata)),
  paste0("  LOW_Q1: ", as.integer(group_counts["LOW_Q1"])),
  paste0("  HIGH_Q4: ", as.integer(group_counts["HIGH_Q4"])),
  paste0(
    "  Unique patients: ",
    length(unique(sample_metadata$patient_id))
  ),
  "",
  "3. PCA",
  paste0("  Genes in canonical VST: ", nrow(vst_matrix)),
  paste0("  Signature rows excluded: ", n_signature_rows),
  paste0("  Genes used for PCA: ", nrow(vst_pca)),
  paste0(
    "  PC1 variance explained: ",
    round(variance_explained[1], 4),
    "%"
  ),
  paste0(
    "  PC2 variance explained: ",
    round(variance_explained[2], 4),
    "%"
  ),
  paste0("  Output: ", output_paths$pca),
  "",
  "4. Volcano",
  paste0(
    "  Effect-size fallback rows: ",
    sum(fallback_rows)
  ),
  paste0("  UP in HIGH_Q4: ", n_up),
  paste0("  DOWN in HIGH_Q4: ", n_down),
  paste0("  Output: ", output_paths$volcano),
  "",
  "5. Selected Hallmark internal control",
  paste0(
    "  Selected pathways requested: ",
    length(selected_hallmark_ids)
  ),
  paste0(
    "  Selected pathways passing FDR < 0.05: ",
    nrow(selected_hallmarks)
  ),
  paste0(
    "  Output: ",
    output_paths$selected_hallmark_barplot
  ),
  "  Manuscript status: internal control, not a current panel",
  "",
  "6. EMT GSEA",
  paste0("  Ranked genes: ", number_ranked_genes),
  paste0("  EMT genes represented: ", number_emt_genes),
  paste0("  Manual ES: ", signif(manual_es, 10)),
  paste0("  Canonical fgsea ES: ", signif(emt_fgsea_es, 10)),
  paste0(
    "  Absolute ES difference: ",
    format(manual_es_difference, scientific = TRUE)
  ),
  paste0("  NES: ", signif(emt_nes, 10)),
  paste0("  FDR: ", signif(emt_fdr, 10)),
  paste0("  Output: ", output_paths$emt_gsea),
  "",
  "7. Figures generated",
  paste0("  Publication: ", output_paths$pca),
  paste0("  Publication: ", output_paths$volcano),
  paste0("  Publication: ", output_paths$emt_gsea),
  paste0(
    "  Internal control: ",
    output_paths$selected_hallmark_barplot
  ),
  "",
  "8. Figures intentionally not generated",
  "  GSEA_Hallmark_SIGNIFICANT_NES_barplot_ALL.pdf",
  "  Heatmap_DEGs_*.pdf",
  "  Heatmap_EMT_Q1Q4_Canonical.pdf",
  "",
  "Final status: PASS"
)

writeLines(
  qc_lines,
  output_paths$qc,
  useBytes = TRUE
)

required_outputs <- unlist(
  output_paths,
  use.names = FALSE
)

missing_outputs <- required_outputs[
  !file.exists(required_outputs)
]

if (length(missing_outputs) > 0) {
  fail(
    "Required outputs were not generated: ",
    paste(missing_outputs, collapse = ", ")
  )
}

msg("PCA:", output_paths$pca)
msg("Volcano:", output_paths$volcano)
msg("Selected Hallmark internal control:", output_paths$selected_hallmark_barplot)
msg("EMT GSEA:", output_paths$emt_gsea)
msg("Metadata:", output_paths$metadata)
msg("QC:", output_paths$qc)
msg("Final status: PASS")
